### ISSUE TITLE
Nested Folders

### ISSUE THREAD

**Issue by lerejbox** [lerejbox/AiNotes#15]
I currently have a bug in the nested folder feature. When i create a new nested folder, let's call this A, it will create an additional folder outside of the parent folder B. This parent folder is somewhat linked to the nested folder in a weird way. Here are my observations:

1. If I create a new nested chat in A, it will create a new nested chat in B instead.
2. If I create a new nested chat in B, it will create a new nested chat in B but no in A
3. If i click on folder A, it will display/hide the chats in B instead
4. If i rename folder A, it does not rename folder B and vice versa
5. If i delete folder A, it will delete folder B and vice versa

**Comment by cwnm** [comment]
closed as resolved
